web:
  nginx:
    customLivenessProbe:
      httpGet:
        host: 127.0.0.1
        port: "{{ .Values.web.nginx.port }}"
        path: /status
    customReadinessProbe:
      httpGet:
        host: 127.0.0.1
        port: "{{ .Values.web.nginx.port }}"
        path: /status
  phpfpm:
    customLivenessProbe:
      tcpSocket:
        host: 127.0.0.1
        port: 9000
    customReadinessProbe:
      exec:
        command: [ls]
