# define version
version: 1.0.0
image:
  repository: php
  tag: 8.0-fpm-alpine
  imagePullPolicy: IfNotPresent

web:
  nginx:
    image:
      repository: local/nginx
      tag: latest
      imagePullPolicy: IfNotPresent
