# define global image
image:
  repository: philippev/helmchart-php
  tag: latest
  imagePullPolicy: IfNotPresent

web:
  nginx:
    image:
      repository: philippev/helmchart-nginx
      tag: latest
      imagePullPolicy: IfNotPresent
