# define locally image
crons:
  - name: cron1
    enabled: true
    schedule: "* * * * *"
    command: echo 'cron 1'
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: Always
  - name: cron2
    enabled: true
    schedule: "* * * * *"
    command: echo 'cron 2'
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: Always

migrations:
  - name: migration1
    enabled: true
    command: php -r 'phpinfo();'
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: Always

web:
  php:
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: IfNotPresent
  nginx:
    image:
      repository: philippev/helmchart-nginx
      tag: latest
      imagePullPolicy: IfNotPresent

workers:
  - name: worker1
    enabled: true
    replica: 1
    command: while true; do echo 'worker 1'; sleep 10; done
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: IfNotPresent
  - name: worker2
    enabled: true
    replica: 1
    command: while true; do echo 'worker 2'; sleep 10; done
    image:
      repository: philippev/helmchart-php
      tag: latest
      imagePullPolicy: IfNotPresent
