{{- range .Values.crons }}
{{- if .enabled | default true }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "symfony.fullname" $ }}-cron-{{ .name }}
  labels:
    {{- include "symfony.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cron-{{ .name }}
  {{- if $.Values.commonLabels }}
    {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonLabels "global" $) | nindent 4 }}
  {{- end }}
{{- if $.Values.commonAnnotations }}
  annotations: {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonAnnotations "global" $) | nindent 4 }}
{{- end }}
data: {{- include "symfony.secret.env" (dict "context" . "global" $) | nindent 2 }}
{{- end }}
{{- end }}
