{{- range .Values.migrations }}
{{- if .enabled | default true }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "symfony.fullname" $ }}-migration-{{ .name }}
  labels:
    {{- include "symfony.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migration-{{ .name }}
  {{- if $.Values.commonLabels }}
    {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonLabels "global" $) | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- if $.Values.commonAnnotations }}
    {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonAnnotations "global" $) | nindent 4 }}
  {{- end }}
spec:
  activeDeadlineSeconds: {{ .timeout | default 60 }}
  backoffLimit: {{ .backoffLimit | default 0 }}
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "symfony.labels" $ | nindent 8 }}
        app.kubernetes.io/component: migration-{{ .name }}
      {{- if $.Values.commonLabels }}
        {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonLabels "global" $) | nindent 8 }}
      {{- end }}
      annotations:
        checksum/secret.env: {{ include "symfony.secret.env" (dict "context" . "global" $) | sha256sum }}
      {{- if $.Values.commonAnnotations }}
        {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonAnnotations "global" $) | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .restartPolicy | default "Never" }}
      initContainers: {{- include "symfony.initContainers.waiting" $ | nindent 8 }}
      containers:
        - name: {{ .name }}
        {{- if .image }}
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
        {{- else }}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- end }}
          command: ['/bin/sh']
          args:
            - '-c'
            - {{ .command }}
          envFrom:
            - secretRef:
                name: {{ include "symfony.fullname" $ }}-migration-{{ .name }}
        {{- if .resources }}
          resources: {{- toYaml .resources | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}
