{{- range .Values.migrations }}
{{- if .enabled | default true }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "symfony.fullname" $ }}-migration-{{ .name }}
  labels:
    {{- include "symfony.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migration-{{ .name }}
  {{- if $.Values.commonLabels }}
    {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonLabels "global" $) | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- if $.Values.commonAnnotations }}
    {{- include "symfony.tplvalues.render" (dict "value" $.Values.commonAnnotations "global" $) | nindent 4 }}
  {{- end }}
data: {{- include "symfony.secret.env" (dict "context" . "global" $) | nindent 2 }}
{{- end }}
{{- end }}
