{{- range .Values.migrations }}
{{- if .enabled | default true }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "symfony.fullname" $ }}-migration-{{ .name }}
  labels:
    {{- include "symfony.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migration-{{ .name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data: {{- include "symfony.secret.env" (dict "context" . "global" $) | nindent 2 }}
{{- end }}
{{- end }}
