{{- if .Values.web.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "symfony.fullname" . }}-web
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      {{- include "symfony.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  replicas: {{ .Values.web.replica }}
  template:
    metadata:
      labels:
        {{- include "symfony.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/secret.env: {{ include "symfony.secret.env" (dict "context" .Values.web.phpfpm "global" .) | sha256sum }}
        checksum/configmap.nginx: {{ include (print .Template.BasePath "/web/configmap.yaml") . | sha256sum }}
    spec:
      initContainers: {{- include "symfony.initContainers.waiting" . | nindent 8 }}
      containers:
        - name: nginx
          image: {{ .Values.web.nginx.image.repository }}:{{ .Values.web.nginx.image.tag }}
          imagePullPolicy: {{ .Values.web.nginx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.nginx.port }}
          volumeMounts:
          {{- if .Values.web.nginx.config.main }}
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- end }}
          {{- if .Values.web.nginx.config.serverBlock }}
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          {{- end }}
        {{- if .Values.web.nginx.customLivenessProbe }}
          livenessProbe: {{- include "symfony.tplvalues.render" (dict "value" .Values.web.nginx.customLivenessProbe "global" .) | nindent 12 }}
        {{- else }}
          livenessProbe:
            httpGet:
              port: { { .Values.web.nginx.port } }
              path: /healthz
            periodSeconds: {{ .Values.web.nginx.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.nginx.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.web.nginx.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.web.nginx.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.web.nginx.customReadinessProbe }}
          readinessProbe: {{- include "symfony.tplvalues.render" (dict "value" .Values.web.nginx.customReadinessProbe "global" .) | nindent 12 }}
        {{- else }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.web.nginx.port }}
            initialDelaySeconds: {{ .Values.web.nginx.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.nginx.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.nginx.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.web.nginx.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.web.nginx.readinessProbe.failureThreshold }}
        {{- end }}
          resources: {{- toYaml .Values.web.nginx.resources | nindent 12 }}
        - name: phpfpm
        {{- if and .Values.web.phpfpm.image }}
          image: {{ .Values.web.phpfpm.image.repository }}:{{ .Values.web.phpfpm.image.tag }}
          imagePullPolicy: {{ .Values.web.phpfpm.image.pullPolicy }}
        {{- else }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "symfony.fullname" . }}-web
        {{- if .Values.web.phpfpm.customLivenessProbe }}
          livenessProbe: {{- include "symfony.tplvalues.render" (dict "value" .Values.web.phpfpm.customLivenessProbe "global" .) | nindent 12 }}
        {{- else }}
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.web.phpfpm.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.phpfpm.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.phpfpm.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.web.phpfpm.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.web.phpfpm.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.web.phpfpm.customReadinessProbe }}
          readinessProbe: {{- include "symfony.tplvalues.render" (dict "value" .Values.web.phpfpm.customReadinessProbe "global" .) | nindent 12 }}
        {{- else }}
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.web.phpfpm.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.phpfpm.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.phpfpm.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.web.phpfpm.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.web.phpfpm.readinessProbe.failureThreshold }}
        {{- end }}
          resources: {{- toYaml .Values.web.phpfpm.resources | nindent 12 }}
      {{- if .Values.metrics.enabled }}
        - name: nginx-metrics
          image: {{ .Values.metrics.nginx.image.repository }}:{{ .Values.metrics.nginx.image.tag }}
          imagePullPolicy: {{ .Values.metrics.nginx.image.pullPolicy }}
          args:
            - '-nginx.scrape-uri'
            - '{{ .Values.metrics.nginx.statusUrl }}'
            - '-web.listen-address'
            - ':{{ .Values.metrics.nginx.port }}'
            - '-web.telemetry-path'
            - '{{ .Values.metrics.nginx.path }}'
          ports:
            - containerPort: {{ .Values.metrics.nginx.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.metrics.nginx.path }}
              port: {{ .Values.metrics.nginx.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.metrics.nginx.path }}
              port: {{ .Values.metrics.nginx.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources: {{- toYaml .Values.metrics.nginx.resources | nindent 12 }}
        - name: phpfpm-metrics
          image: {{ .Values.metrics.phpfpm.image.repository }}:{{ .Values.metrics.phpfpm.image.tag }}
          imagePullPolicy: {{ .Values.metrics.phpfpm.image.pullPolicy }}
          args:
            - '--addr'
            - ':{{ .Values.metrics.phpfpm.port }}'
            - '--fastcgi'
            - '{{ .Values.metrics.phpfpm.statusUrl }}'
            - '--web.telemetry-path'
            - '{{ .Values.metrics.phpfpm.path }}'
          ports:
            - containerPort: {{ .Values.metrics.phpfpm.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.metrics.phpfpm.path }}
              port: {{ .Values.metrics.phpfpm.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.metrics.phpfpm.path }}
              port: {{ .Values.metrics.phpfpm.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources: {{- toYaml .Values.metrics.phpfpm.resources | nindent 12 }}
      {{- end }}
      volumes:
        - name: nginx
          configMap:
            name: {{ include "symfony.fullname" . }}-web-nginx
{{- end }}
