{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "symfony.fullname" . }}-web
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if .Values.commonLabels }}
    {{- include "symfony.tplvalues.render" (dict "value" .Values.commonLabels "global" .) | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.web.ingress.annotations }}
      {{- include "symfony.tplvalues.render" ( dict "value" .Values.web.ingress.annotations "global" .) | nindent 4 }}
  {{- end }}
  {{- if .Values.web.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- include "symfony.tplvalues.render" (dict "value" .Values.commonAnnotations "global" .) | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- if .Values.web.ingress.hostname }}
    - host: {{ .Values.web.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path }}
            pathType: {{ .Values.web.ingress.pathType }}
            backend:
              service:
                name: {{ include "symfony.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
  {{- end }}
  {{- range .Values.web.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ include "symfony.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
  {{- end }}
{{- if .Values.web.ingress.certManager}}
  tls:
    - hosts:
        - {{ .Values.web.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.web.ingress.hostname }}
{{- end }}
{{- end }}
