{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "symfony.fullname" . }}-web
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data: {{- include "symfony.secret.env" (dict "context" .Values.web.phpfpm "global" .) | nindent 2 }}
{{- end }}
