{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "symfony.fullname" . }}-web
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- if .Values.commonLabels }}
    {{- include "symfony.tplvalues.render" (dict "value" .Values.commonLabels "global" .) | nindent 4 }}
  {{- end }}
{{- if .Values.commonAnnotations }}
  annotations: {{- include "symfony.tplvalues.render" (dict "value" .Values.commonAnnotations "global" .) | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.web.service.type }}
{{- if and (eq .Values.web.service.type "ClusterIP") .Values.web.service.clusterIP }}
  clusterIP: {{ .Values.web.service.clusterIP }}
{{- end}}
{{- if and (eq .Values.web.service.type "LoadBalancer") .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.web.service.loadBalancerIP }}
{{- end}}
{{- if and (eq .Values.web.service.type "LoadBalancer") .Values.web.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.web.service.loadBalancerSourceRanges | nindent 4 }}
{{- end}}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.nginx.port }}
    {{- if and (or (eq .Values.web.service.type "LoadBalancer") (eq .Values.web.service.type "NodePort")) .Values.web.service.nodePort }}
       nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  {{- if .Values.metrics.enabled }}
    - name: nginx-metrics
      port: {{ .Values.metrics.nginx.port }}
      targetPort: {{ .Values.metrics.nginx.port }}
    - name: phpfpm-metrics
      port: {{ .Values.metrics.phpfpm.port }}
      targetPort: {{ .Values.metrics.phpfpm.port }}
  {{- end }}
  selector:
    {{- include "symfony.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
