name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2
        with:
          command: lint

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        uses: 'docker://jnorwood/helm-docs:v1.4.0'
      - name: check if docs is up do date
        run: git diff --exit-code
