name: CI

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint_chart:
    name: Lint Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: lint
          version: v3.3.1

  lint_docs:
    name: Check if Charts Documentation is up do date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        uses: 'docker://jnorwood/helm-docs:v1.4.0'
      - name: check if docs is up do date
        run: git diff --exit-code

  install_chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.18.8
          - v1.19.4
          - v1.20.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.1.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: install
          version: v3.3.1
