version: 0.1.0
image:
  repository: local/test/php
  tag: latest
  imagePullPolicy: IfNotPresent

env:
  TIMEZONE: utc
  TRUSTED_PROXIES: 0.0.0.0/0
  DATABASE_URL: mysql://test:{password}@mysql:3306/test
  MESSENGER_TRANSPORT_DSN: amqp://test:{password}@rabbitmq:5672/%2F/messages
  REDIS_DSN: redis://{password}@redis-master:6379

migrations:
  - name: doctrine
    enabled: true
    command: bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
    timeout: 60
  - name: messenger
    enabled: true
    command: bin/console messenger:setup-transports --no-interaction
    timeout: 60

web:
  replica: 3
  nginx:
    image:
      repository: local/test/nginx
      tag: latest
      imagePullPolicy: IfNotPresent

workers:
  - name: messenger
    enabled: true
    replica: 3
    command: bin/console messenger:consume --memory-limit=128M --time-limit=600

crons:
  - name: test
    enabled: true
    schedule: "*/5 * * * *"
    command: bin/console doctrine:query:sql 'SELECT 1;'

dependencies:
  services:
    - name: mysql
      host: mysql
      port: 3306
    - name: rabbitmq
      host: rabbitmq
      port: 5672
    - name: redis
      host: redis-master
      port: 6379
